<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailSenderService\EmailSenderService.csproj" />
    <ProjectReference Include="..\LoggerService\LoggerService.csproj" />
    <ProjectReference Include="..\Medico.Data\Medico.Data.csproj" />
    <ProjectReference Include="..\Medico.Repository\Medico.Repository.csproj" />
  </ItemGroup>

</Project>
