// <auto-generated />
using System;
using Medico.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medico.Data.Migrations
{
    [DbContext(typeof(MedicoContext))]
    [Migration("20260210034339_InitialAzureFixed")]
    partial class InitialAzureFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medico.Data.Entities.AllergyMaster", b =>
                {
                    b.Property<int>("Allergyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Allergyid"));

                    b.Property<string>("Allerginicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modfieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partialsequences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Allergyid");

                    b.ToTable("allergy_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.Appointment", b =>
                {
                    b.Property<int>("Appointmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Appointmentid"));

                    b.Property<int>("Appointmentstatusid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Apptdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Nurseid")
                        .HasColumnType("int");

                    b.Property<int?>("Patientid")
                        .HasColumnType("int");

                    b.Property<int?>("Physicianid")
                        .HasColumnType("int");

                    b.Property<string>("RejectCancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Timeslotid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Appointmentid");

                    b.HasIndex("Appointmentstatusid");

                    b.HasIndex("Nurseid");

                    b.HasIndex("Patientid");

                    b.HasIndex("Physicianid");

                    b.HasIndex("Timeslotid");

                    b.ToTable("appointment", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentActionMaster", b =>
                {
                    b.Property<int>("Actionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Actionid"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Actionid");

                    b.ToTable("appointment_action_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentStatusMaster", b =>
                {
                    b.Property<int>("Appointmentstatusid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Appointmentstatusid"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Roleid")
                        .HasColumnType("int");

                    b.HasKey("Appointmentstatusid");

                    b.HasIndex("Roleid");

                    b.ToTable("appointment_status_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentTimeslotsMaster", b =>
                {
                    b.Property<int>("Timeslotid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Timeslotid"));

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Timeslotid");

                    b.ToTable("appointment_timeslots_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.CityMaster", b =>
                {
                    b.Property<int>("Cityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cityid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stateid")
                        .HasColumnType("int");

                    b.HasKey("Cityid");

                    b.HasIndex("Stateid");

                    b.ToTable("city_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pairfor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("configuration", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.CountryMaster", b =>
                {
                    b.Property<int>("Countryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Countryid"));

                    b.Property<string>("Countrycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Countryid");

                    b.ToTable("country_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.DemographicDetails", b =>
                {
                    b.Property<int>("Personid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personid"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Cityid")
                        .HasColumnType("int");

                    b.Property<string>("Contactnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dialcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Languageknown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Titleid")
                        .HasColumnType("int");

                    b.HasKey("Personid");

                    b.HasIndex("Cityid");

                    b.HasIndex("Titleid");

                    b.ToTable("demographic_details", "person");
                });

            modelBuilder.Entity("Medico.Data.Entities.DepartmentMaster", b =>
                {
                    b.Property<int>("Departmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Departmentid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Departmentid");

                    b.ToTable("department_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.DiagnosisMaster", b =>
                {
                    b.Property<int>("Diagnosisid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Diagnosisid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("Modfieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Diagnosisid");

                    b.ToTable("diagnosis_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.DialcodeMaster", b =>
                {
                    b.Property<int>("Dialcodeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dialcodeid"));

                    b.Property<int>("Countryid")
                        .HasColumnType("int");

                    b.Property<string>("Dialcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dialcodeid");

                    b.HasIndex("Countryid");

                    b.ToTable("dialcode_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.Emails", b =>
                {
                    b.Property<int>("Emailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emailid"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Issent")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Sentdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emailid");

                    b.ToTable("emails", "users");
                });

            modelBuilder.Entity("Medico.Data.Entities.Emailtemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("emailtemplates", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.EmergencyContInfo", b =>
                {
                    b.Property<int>("Emergencycontactid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emergencycontactid"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Allowedaccess")
                        .HasColumnType("bit");

                    b.Property<string>("Contactnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dialcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Patientid")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emergencycontactid");

                    b.HasIndex("Patientid");

                    b.ToTable("emergency_cont_info", "person");
                });

            modelBuilder.Entity("Medico.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employeeid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("int");

                    b.Property<float?>("Experience")
                        .HasColumnType("real");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Spacilities")
                        .HasColumnType("json");

                    b.Property<string>("Worklocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employeeid");

                    b.HasIndex("Departmentid");

                    b.ToTable("employee", "hospital");
                });

            modelBuilder.Entity("Medico.Data.Entities.EthenicityMaster", b =>
                {
                    b.Property<int>("Ethenicityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ethenicityid"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ethenicityid");

                    b.ToTable("ethenicity_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.LanguageMaster", b =>
                {
                    b.Property<int>("Languageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Languageid"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Languageid");

                    b.ToTable("language_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.LoginHistory", b =>
                {
                    b.Property<int>("Loginhistoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Loginhistoryid"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Ipaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Loggedoutsuccessfully")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Logindatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Loginhistoryid");

                    b.HasIndex("Userid");

                    b.ToTable("login_history", "users");
                });

            modelBuilder.Entity("Medico.Data.Entities.MedicinDetails", b =>
                {
                    b.Property<int>("Medicindetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Medicindetailid"));

                    b.Property<string>("Dosagedetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Medicinid")
                        .HasColumnType("int");

                    b.Property<int>("Patientprescriptionid")
                        .HasColumnType("int");

                    b.Property<string>("Prescriptionnote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Medicindetailid");

                    b.HasIndex("Medicinid");

                    b.HasIndex("Patientprescriptionid");

                    b.ToTable("medicin_details", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.MedicinMaster", b =>
                {
                    b.Property<int>("Medicinid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Medicinid"));

                    b.Property<string>("Activeingredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Appno")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drugname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("Medicinnumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modfieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencedrug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Medicinid");

                    b.ToTable("medicin_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Appointmentid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Isread")
                        .HasColumnType("bit");

                    b.Property<int?>("NotificationNavigationNotificationid")
                        .HasColumnType("int");

                    b.Property<int?>("Notificationid")
                        .HasColumnType("int");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Appointmentid");

                    b.HasIndex("NotificationNavigationNotificationid");

                    b.HasIndex("Userid");

                    b.ToTable("notification", "users");
                });

            modelBuilder.Entity("Medico.Data.Entities.NotificationTemplates", b =>
                {
                    b.Property<int>("Notificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notificationid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Isdeprecated")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Notificationid");

                    b.ToTable("notification_templates", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.PasswordChangeRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Randomhashid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("password_change_requests", "users");
                });

            modelBuilder.Entity("Medico.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Patientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patientid"));

                    b.PrimitiveCollection<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Allergiesdescription")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Emergencycontacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Patientid");

                    b.HasIndex("Personid");

                    b.HasIndex("Userid");

                    b.ToTable("patient", "hospital");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientDiagnosis", b =>
                {
                    b.Property<int>("Patientdiagnosisid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patientdiagnosisid"));

                    b.Property<int?>("Appointmentid")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Diagnosisid")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosisnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.HasKey("Patientdiagnosisid");

                    b.HasIndex("Appointmentid");

                    b.HasIndex("Diagnosisid");

                    b.ToTable("patient_diagnosis", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientPrescription", b =>
                {
                    b.Property<int>("Patientprescriptionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patientprescriptionid"));

                    b.Property<int>("Appointmentid")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.HasKey("Patientprescriptionid");

                    b.HasIndex("Appointmentid");

                    b.ToTable("patient_prescription", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientProcedureDetails", b =>
                {
                    b.Property<int>("Patientprocedureid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patientprocedureid"));

                    b.Property<int>("Appointmentid")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Procedureid")
                        .HasColumnType("int");

                    b.Property<string>("Procedurenote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patientprocedureid");

                    b.HasIndex("Appointmentid");

                    b.HasIndex("Procedureid");

                    b.ToTable("patient_procedure_details", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientVisitDetails", b =>
                {
                    b.Property<int>("Patientvisitdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patientvisitdetailid"));

                    b.Property<int?>("Appointmentid")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vitalsigns")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patientvisitdetailid");

                    b.HasIndex("Appointmentid");

                    b.ToTable("patient_visit_details", "appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.ProcedureMaster", b =>
                {
                    b.Property<int>("Procedureid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Procedureid"));

                    b.Property<string>("Approach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("Modfieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Procedureid");

                    b.ToTable("procedure_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.RoleMaster", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Roleid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Roleid");

                    b.ToTable("role_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.SpecialityMaster", b =>
                {
                    b.Property<int>("Specialityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Specialityid"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Roleid")
                        .HasColumnType("int");

                    b.HasKey("Specialityid");

                    b.HasIndex("Roleid");

                    b.ToTable("speciality_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.StateMaster", b =>
                {
                    b.Property<int>("Stateid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stateid"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Countryid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stateid");

                    b.HasIndex("Countryid");

                    b.ToTable("state_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.StatusMaster", b =>
                {
                    b.Property<int>("Statusid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Statusid"));

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Statusid");

                    b.ToTable("status_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.TitleMaster", b =>
                {
                    b.Property<int>("Titleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Titleid"));

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Titleid");

                    b.ToTable("title_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Userid"));

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employeeid")
                        .HasColumnType("int");

                    b.Property<bool?>("Isfirstlogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Islocked")
                        .HasColumnType("bit");

                    b.Property<string>("Lastchangepassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<int>("Roleid")
                        .HasColumnType("int");

                    b.Property<int?>("Statusid")
                        .HasColumnType("int");

                    b.HasKey("Userid");

                    b.HasIndex("Employeeid");

                    b.HasIndex("Personid");

                    b.HasIndex("Roleid");

                    b.HasIndex("Statusid");

                    b.ToTable("user", "users");
                });

            modelBuilder.Entity("Medico.Data.Entities.VitalSignsMaster", b =>
                {
                    b.Property<int>("Vitalsignid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vitalsignid"));

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Imgurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vitalsignid");

                    b.ToTable("vital_signs_master", "master");
                });

            modelBuilder.Entity("Medico.Data.Entities.Appointment", b =>
                {
                    b.HasOne("Medico.Data.Entities.AppointmentStatusMaster", "Appointmentstatus")
                        .WithMany("Appointment")
                        .HasForeignKey("Appointmentstatusid")
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.Employee", "Nurse")
                        .WithMany("AppointmentNurse")
                        .HasForeignKey("Nurseid")
                        .HasConstraintName("fk_nurseid");

                    b.HasOne("Medico.Data.Entities.Patient", "Patient")
                        .WithMany("Appointment")
                        .HasForeignKey("Patientid")
                        .HasConstraintName("fk_patientid");

                    b.HasOne("Medico.Data.Entities.Employee", "Physician")
                        .WithMany("AppointmentPhysician")
                        .HasForeignKey("Physicianid")
                        .HasConstraintName("fk_physicianid");

                    b.HasOne("Medico.Data.Entities.AppointmentTimeslotsMaster", "Timeslot")
                        .WithMany("Appointment")
                        .HasForeignKey("Timeslotid");

                    b.Navigation("Appointmentstatus");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Physician");

                    b.Navigation("Timeslot");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentStatusMaster", b =>
                {
                    b.HasOne("Medico.Data.Entities.RoleMaster", "Role")
                        .WithMany("AppointmentStatusMaster")
                        .HasForeignKey("Roleid");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Medico.Data.Entities.CityMaster", b =>
                {
                    b.HasOne("Medico.Data.Entities.StateMaster", "State")
                        .WithMany("CityMaster")
                        .HasForeignKey("Stateid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Medico.Data.Entities.DemographicDetails", b =>
                {
                    b.HasOne("Medico.Data.Entities.CityMaster", "City")
                        .WithMany("DemographicDetails")
                        .HasForeignKey("Cityid");

                    b.HasOne("Medico.Data.Entities.TitleMaster", "Title")
                        .WithMany("DemographicDetails")
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Medico.Data.Entities.DialcodeMaster", b =>
                {
                    b.HasOne("Medico.Data.Entities.CountryMaster", "Country")
                        .WithMany("DialcodeMaster")
                        .HasForeignKey("Countryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Medico.Data.Entities.EmergencyContInfo", b =>
                {
                    b.HasOne("Medico.Data.Entities.Patient", "Patient")
                        .WithMany("EmergencyContInfo")
                        .HasForeignKey("Patientid");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medico.Data.Entities.Employee", b =>
                {
                    b.HasOne("Medico.Data.Entities.DepartmentMaster", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("Departmentid");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Medico.Data.Entities.LoginHistory", b =>
                {
                    b.HasOne("Medico.Data.Entities.User", "User")
                        .WithMany("LoginHistory")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.MedicinDetails", b =>
                {
                    b.HasOne("Medico.Data.Entities.MedicinMaster", "Medicin")
                        .WithMany("MedicinDetails")
                        .HasForeignKey("Medicinid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.PatientPrescription", "Patientprescription")
                        .WithMany("MedicinDetails")
                        .HasForeignKey("Patientprescriptionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicin");

                    b.Navigation("Patientprescription");
                });

            modelBuilder.Entity("Medico.Data.Entities.Notification", b =>
                {
                    b.HasOne("Medico.Data.Entities.Appointment", "Appointment")
                        .WithMany("Notification")
                        .HasForeignKey("Appointmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.NotificationTemplates", "NotificationNavigation")
                        .WithMany("Notification")
                        .HasForeignKey("NotificationNavigationNotificationid");

                    b.HasOne("Medico.Data.Entities.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("NotificationNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.Patient", b =>
                {
                    b.HasOne("Medico.Data.Entities.DemographicDetails", "Person")
                        .WithMany("Patient")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_person");

                    b.HasOne("Medico.Data.Entities.User", "User")
                        .WithMany("Patient")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_user");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientDiagnosis", b =>
                {
                    b.HasOne("Medico.Data.Entities.Appointment", "Appointment")
                        .WithMany("PatientDiagnosis")
                        .HasForeignKey("Appointmentid");

                    b.HasOne("Medico.Data.Entities.DiagnosisMaster", "Diagnosis")
                        .WithMany("PatientDiagnosis")
                        .HasForeignKey("Diagnosisid");

                    b.Navigation("Appointment");

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientPrescription", b =>
                {
                    b.HasOne("Medico.Data.Entities.Appointment", "Appointment")
                        .WithMany("PatientPrescription")
                        .HasForeignKey("Appointmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientProcedureDetails", b =>
                {
                    b.HasOne("Medico.Data.Entities.Appointment", "Appointment")
                        .WithMany("PatientProcedureDetails")
                        .HasForeignKey("Appointmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.ProcedureMaster", "Procedure")
                        .WithMany("PatientProcedureDetails")
                        .HasForeignKey("Procedureid");

                    b.Navigation("Appointment");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientVisitDetails", b =>
                {
                    b.HasOne("Medico.Data.Entities.Appointment", "Appointment")
                        .WithMany("PatientVisitDetails")
                        .HasForeignKey("Appointmentid");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.SpecialityMaster", b =>
                {
                    b.HasOne("Medico.Data.Entities.RoleMaster", "Role")
                        .WithMany("SpecialityMaster")
                        .HasForeignKey("Roleid");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Medico.Data.Entities.StateMaster", b =>
                {
                    b.HasOne("Medico.Data.Entities.CountryMaster", "Country")
                        .WithMany("StateMaster")
                        .HasForeignKey("Countryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Medico.Data.Entities.User", b =>
                {
                    b.HasOne("Medico.Data.Entities.Employee", "Employee")
                        .WithMany("User")
                        .HasForeignKey("Employeeid");

                    b.HasOne("Medico.Data.Entities.DemographicDetails", "Person")
                        .WithMany("User")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.RoleMaster", "Role")
                        .WithMany("User")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medico.Data.Entities.StatusMaster", "Status")
                        .WithMany("User")
                        .HasForeignKey("Statusid");

                    b.Navigation("Employee");

                    b.Navigation("Person");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Medico.Data.Entities.Appointment", b =>
                {
                    b.Navigation("Notification");

                    b.Navigation("PatientDiagnosis");

                    b.Navigation("PatientPrescription");

                    b.Navigation("PatientProcedureDetails");

                    b.Navigation("PatientVisitDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentStatusMaster", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.AppointmentTimeslotsMaster", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medico.Data.Entities.CityMaster", b =>
                {
                    b.Navigation("DemographicDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.CountryMaster", b =>
                {
                    b.Navigation("DialcodeMaster");

                    b.Navigation("StateMaster");
                });

            modelBuilder.Entity("Medico.Data.Entities.DemographicDetails", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.DepartmentMaster", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Medico.Data.Entities.DiagnosisMaster", b =>
                {
                    b.Navigation("PatientDiagnosis");
                });

            modelBuilder.Entity("Medico.Data.Entities.Employee", b =>
                {
                    b.Navigation("AppointmentNurse");

                    b.Navigation("AppointmentPhysician");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.MedicinMaster", b =>
                {
                    b.Navigation("MedicinDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.NotificationTemplates", b =>
                {
                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Medico.Data.Entities.Patient", b =>
                {
                    b.Navigation("Appointment");

                    b.Navigation("EmergencyContInfo");
                });

            modelBuilder.Entity("Medico.Data.Entities.PatientPrescription", b =>
                {
                    b.Navigation("MedicinDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.ProcedureMaster", b =>
                {
                    b.Navigation("PatientProcedureDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.RoleMaster", b =>
                {
                    b.Navigation("AppointmentStatusMaster");

                    b.Navigation("SpecialityMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.StateMaster", b =>
                {
                    b.Navigation("CityMaster");
                });

            modelBuilder.Entity("Medico.Data.Entities.StatusMaster", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Medico.Data.Entities.TitleMaster", b =>
                {
                    b.Navigation("DemographicDetails");
                });

            modelBuilder.Entity("Medico.Data.Entities.User", b =>
                {
                    b.Navigation("LoginHistory");

                    b.Navigation("Notification");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
